
services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend_restaurant
    env_file: .env
    depends_on:
      - backend
    networks:
      - spring_network

  backend:
    build:
      context: ./backend
    container_name: backend_restaurant
    env_file: .env
    environment:
      - SPRING_PROFILES_ACTIVE=generateData
    depends_on:
      - postgres
    networks:
      - spring_network

  postgres:
      image: postgres:15.2
      container_name: postgres-restaurant
      env_file: .env
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        JDBC_URL: ${JDBC_URL}
      volumes:
        - pgdata:/var/lib/postgresql/data
      networks:
        - spring_network
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
        interval: 30s
        retries: 3
        start_period: 5s
        timeout: 10s

volumes:
  pgdata:  # Ensures PostgreSQL data persists even if the container restarts

networks:
  spring_network:
