logging:
  file.name: ./log/backend.log
  level:
    org.springframework.web: DEBUG
    root: INFO

spring:
  datasource:
    url: ${POSTGRES_URL}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}                                    #
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 16
        jdbc:
          lob:
            non_contextual_creation: true

security:
  auth:
    header: Authorization
    prefix: "Bearer "
    login-uri: /api/v1/authentication
    white-list:
      # Browser requests
      - /
      - /favicon.ico
      - /csrf
      # Swagger
      - /v2/api-docs
      - /swagger-resources/**
      - /webjars/**
      - /swagger-ui.html
  jwt:
    # Use http://www.allkeysgenerator.com/ to generate secrets
    secret: ${JWT_SECRET}
    type: JWT
    issuer: secure-backend
    audience: secure-app
    # 12 hours in milliseconds
    expiration-time: 43200000
