spring:
  datasource:
    url: ${JDBC_URL}              # your Azure Postgres JDBC URL
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate          # validate schema, do NOT create or update in prod
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: WARN
    org.springframework.web: ERROR
