name: Build and deploy backend only

on:
  push:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'microsoft'

      - name: Build backend (skip tests)
        run: mvn clean install -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-jar
          path: ./artifact
          
      - name: Enable debug logging
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - name: Dump debug info (for troubleshooting only)
        run: |
          echo "CLIENT ID SET: [${{ secrets.AZURE_CLIENT_ID != '' }}]"
          echo "TENANT ID SET: [${{ secrets.AZURE_TENANT_ID != '' }}]"
          echo "SUBSCRIPTION ID SET: [${{ secrets.AZURE_SUBSCRIPTION_ID != '' }}]"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'restaurant-backend'
          slot-name: 'Production'
          package: ./artifact/*.jar
